apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-avp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/arfan-pantua/argo-helm.git
    targetRevision: main

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/arfan-pantua/argo-helm.git
    targetRevision: main